index:
    path: /api/users/{email}
    controller: App\Framework\Controller\User\FindUserByEmailController

password_reset:
    path: /api/users/{email}/password-reset
    controller: App\Framework\Controller\User\RequestPasswordResetController
