login:
    path: /api/users/login
    methods:
        - POST
    controller: App\Framework\Controller\User\AuthenticateController

password_reset:
    path: /api/users/password-reset
    methods:
        - POST
    controller: App\Framework\Controller\User\RequestPasswordResetController
